resolver: lts-13.17
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []
ghc-options:
   "$locals": -Wall -fno-warn-unused-do-bind -Wincomplete-record-updates -Wnoncanonical-monad-instances -Wnoncanonical-monadfail-instances -Wincomplete-uni-patterns -Widentities -Wcpp-undef -fhide-source-paths -Wno-missing-home-modules
